import '@/styles/globals.css'

import { GeistMono } from 'geist/font/mono'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '@/trpc/react'
import { cn } from '@/lib/utils'

import localFont from 'next/font/local'

const interVariable = localFont({
  variable: '--font-sans',
  src: '../fonts/InterVariable.woff2',
  weight: '200 700',
  display: 'swap',
  preload: true,
})

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        `font-sans ${interVariable.variable} ${GeistMono.variable} min-h-screen antialiased`,
      )}
    >
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  )
}
